databases:
  - name: book_slot_db
    databaseName: book_slot
    user: book_slot_user

services:
  - type: web
    name: book-slot-backend
    runtime: python
    buildCommand: |-
      pip install -r requirements.txt
      cd backend && alembic upgrade head
    startCommand: |-
      cd backend && uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: book_slot_db
          property: connectionString
    plan: free
