"""Add admins table

Revision ID: 7ef32946c515
Revises: c017d069bd5f
Create Date: 2025-06-24 00:32:43.683573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef32946c515'
down_revision: Union[str, Sequence[str], None] = 'c017d069bd5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_email_slot', 'bookings', ['email', 'slot_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_email_slot', 'bookings', type_='unique')
    # ### end Alembic commands ###
