"""Add created_by and created_at to events table

Revision ID: c017d069bd5f
Revises: 09e20bc8ddcc
Create Date: 2025-06-22 07:15:46.114729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c017d069bd5f'
down_revision: Union[str, Sequence[str], None] = '09e20bc8ddcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add columns as nullable
    op.add_column('events', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('events', sa.Column('created_at', sa.DateTime(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE events SET created_by = 'system', created_at = NOW()")
    
    # Now alter columns to be non-nullable
    op.alter_column('events', 'created_by', nullable=False)
    op.alter_column('events', 'created_at', server_default=sa.text('now()'), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'created_at')
    op.drop_column('events', 'created_by')
    # ### end Alembic commands ###
